import { NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import path from "path";

/**
 * GET /dev-login
 * Development-only auto-login endpoint.
 * Reads keys/dev_token.txt (generated by start.sh --dev) and sets the
 * narad_session cookie, then redirects to /geostrat.
 *
 * Only works when NODE_ENV=development. Returns 404 in production.
 */
export async function GET(request: Request) {
  if (process.env.NODE_ENV !== "development") {
    return new NextResponse("Not Found", { status: 404 });
  }

  // Resolve path relative to the monorepo root (4 levels up from src/app/dev-login)
  const tokenPaths = [
    path.resolve(process.cwd(), "../../keys/dev_token.txt"),
    path.resolve(process.cwd(), "keys/dev_token.txt"),
    path.resolve(process.cwd(), "../keys/dev_token.txt"),
  ];

  let token: string | null = null;
  for (const p of tokenPaths) {
    if (existsSync(p)) {
      token = readFileSync(p, "utf-8").trim();
      break;
    }
  }

  if (!token) {
    return new NextResponse(
      JSON.stringify({
        error: "Dev token not found. Run ./start.sh --dev first.",
        searched: tokenPaths,
      }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }

  const cookieName = process.env.APP_AUTH_COOKIE_NAME?.trim() || "narad_session";
  const redirectTo = new URL(request.url).searchParams.get("to") || "/geostrat";

  const response = NextResponse.redirect(new URL(redirectTo, request.url));
  response.cookies.set(cookieName, token, {
    path: "/",
    httpOnly: false,  // allow JS reads in dev
    secure: false,    // no HTTPS in dev
    sameSite: "lax",
    maxAge: 365 * 24 * 60 * 60, // 1 year
  });

  return response;
}
